# Generated by Django 6.0.2 on 2026-04-21 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ex', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modeltip',
            options={'permissions': [('can_downvote', 'Can downvote its own tips or get permission from admin')]},
        ),
    ]
