# Generated by Django 6.0.2 on 2026-04-21 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex', '0002_alter_modeltip_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycustomuser',
            name='reputation',
            field=models.IntegerField(default=0),
        ),
    ]
