# Generated by Django 6.0.2 on 2026-04-22 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ex', '0003_mycustomuser_reputation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mycustomuser',
            name='reputation',
        ),
    ]
